# -*- coding: utf-8 -*-

titulos = {}
titulos["legal"] = "Aviso Legal"
titulos["privacidad"] = "Politica de Privacidad"
titulos["login"] = "Login"
titulos["index"] = "Index"
titulos["registro"] = "Alta en Ziip"
titulos["home"] = "Home"
titulos["confirmacionMovil"] = "confirmacion Movil"
titulos["peticion"] = "Peticion"
titulos["contactos"] = "Contactos"
titulos["recientes"] = "Recientes"
titulos["ziip"] = "Ziip"
titulos["ajustes"] = "ajustes"
titulos["anonimo"] = "anonimo"
titulos["conecta"] = "conecta"
titulos["celestino"] = "celestino"
titulos["chat"] = "Chat"
titulos["contacto"] = "Contacto"


subtitulos = {}

subtitulos["legal"] = ""
subtitulos["privacidad"]= ""
subtitulos["login"] = "Ziip.es la primera plataforma de contactos completamente anónima"
subtitulos["index"] = "Ziip.es la primera plataforma de contactos completamente anónima"
subtitulos["registro"] = "Subtitulo de registro en Ziip"
subtitulos["home"] = "Ziip.es la primera plataforma de contactos completamente anónima"
subtitulos["confirmacionMovil"] = "Intro"
subtitulos["peticion"] = "Detalle de contacto."
subtitulos["contactos"] = "Tus amigos"
subtitulos["recientes"] = "Contactos recientes"
subtitulos["ziip"] = "Ziip.es la primera plataforma de contactos completamente anónima"
subtitulos["ajustes"] = ""
subtitulos["anonimo"] = "Envía mensajes anónimos."
subtitulos["conecta"] = "Invita a usar ziip.es de forma anónima."
subtitulos["celestino"] = "Contacta con dos personas que deben de conocerse"
subtitulos["chat"] = ""
subtitulos["contacto"] = "Estamos a tu disposición para cualquier duda"
